cache:
  directories:
    - "node_modules"
    - "typings"
language: "node_js"
node_js:
  - "node"

before_install:
  - cd frontend

script:
  - npm install -g codecov
  - npm test

after_success:
  - codecov
