matrix:
  include:
    - name: "Frnotend"
      language: "node_js"
      cache:
        directories:
          - "node_modules"
          - "typings"
      node_js:
        - "node"

      before_install:
        - cd frontend

      script:
        - npm install -g codecov
        - npm test

      after_success:
        - codecov

    - name: "Backend (nightly)"
      language: "rust"
      rust: nightly
