[package]
name = "skarot"
version = "0.1.0"
authors = ["Astra <deifacted@users.noreply.github.com>"]

[dependencies]
byteorder = "1.2"
failure = "0.1"
itertools = "0.7"
lazy_static = "1.0"
rand_core = "0.2"
rand = "0.5"
rocket = "0.3"
rocket_codegen = "0.3"
rocket_contrib = "0.3"